channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip<21
  - datalad
  - pyqt=5
  - numpy=1.23
  - pip:
    - joblib
    - tqdm
    - pillow
    - matplotlib
    - h5py
    - pandas
    - scikit-learn
    - networkx
    - pybind11
    - loky
    - neo>=0.10.0
    - probeinterface
    - MEArec>=1.7.1
    - sphinx-gallery
    - numpydoc
    - numpy<1.24
    - hdbscan
    - numba
    - git+https://github.com/SpikeInterface/spikeinterface.git
    - sphinx_rtd_theme
    - sphinx_gallery
    - numpydoc
