name: 'Show environment'
description: 'A generic description'

inputs: {}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: git-annex version
      run: |
        git-annex version
      shell: bash
    - name: Packages installed
      run: |
        source ~/test_env/bin/activate
        pip list
      shell: bash
    - name: Check ephy_testing_data files
      run: |
        if [ -d "$HOME/spikeinterface_datasets" ]; then
          find $HOME/spikeinterface_datasets
        fi
      shell: bash