name: 'Install packages'

inputs: {}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt install git 
        git config --global user.email "CI@example.com"
        git config --global user.name "CI Almighty"
        python -m venv ~/test_env
        python -m pip install -U pip  # Official recommended way
        source ~/test_env/bin/activate
        pip install tabulate  # This produces summaries at the end
        pip install -e .[test,extractors,full]
      shell: bash
    - name: Force installation of latest dev from key-packages when running dev (not release)
      id: version
      run: |
        source ~/test_env/bin/activate
        if python ./.github/is_spikeinterface_dev.py; then
          echo "Running spikeinterface dev version"
          pip uninstall -y neo
          pip uninstall -y probeinterface
          pip install git+https://github.com/NeuralEnsemble/python-neo
          pip install git+https://github.com/SpikeInterface/probeinterface
        else
          echo "Running tests for release"
        fi
      shell: bash
    - name: git-annex install
      run: |
        wget https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
        tar xvzf git-annex-standalone-amd64.tar.gz
        echo "$(pwd)/git-annex.linux" >> $GITHUB_PATH