name: 'Install packages'

inputs: {}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt install git 
        git config --global user.email "CI@example.com"
        git config --global user.name "CI Almighty"
        python -m venv ${{ github.workspace }}/test_env
        python -m pip install -U pip  # Official recommended way
        source ${{ github.workspace }}/test_env/bin/activate
        pip install tabulate  # This produces summaries at the end
        pip install -e .[test,extractors,full]
      shell: bash