name: Testing deepinterpolation

on:
  pull_request:
    types: [synchronize, opened, reopened]
    branches:
      - main

concurrency:  # Cancel previous workflows on the same pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }} OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install -U pip  # Official recommended way
          # install deepinteprolation
          pip install tensorflow==2.7.0
          pip install deepinterpolation@git+https://github.com/AllenInstitute/deepinterpolation.git
          pip install -e .[full,test_core]
      - name: Test core with pytest
        run: |
          pytest -v src/spikeinterface/preprocessing/deepinterpolation
        shell: bash  # Necessary for pipeline to work on windows
