name: Use pre-commit post merge

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit-post-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pre-commit
        run: |
          python -m pip install pre-commit
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files || true
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PRE_COMMIT_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || (git commit -am "Format code"; git push)
        if: always()